language: python

cache: pip

addons:
  chrome: stable

env:
  - CHROMEDRIVER_VERSION="80.0.3987.106" NODE_VERSION="12.16.1"

install:
  # Setup chrome + chromedriver
  - wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - export SELENIUM_CHROME_BIN="$(which google-chrome-stable)"
  # Setup python env
  - pip install -r requirements.txt
  # Install node and dependencies
  - nvm install ${NODE_VERSION}
  - npm install

script:
  - pytest
  - pylint test/*
