language: python

cache:
  directories:
      - node_modules

env:
  - NODE_VERSION="12.16.1"

before_install:
  - nvm install $NODE_VERSION

addons:
  chrome: 80.0.3987.162

install:
  # Setup chrome + chromedriver
  - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - export SELENIUM_CHROME_BIN="$(which google-chrome-stable)"
  - ${SELENIUM_CHROME_BIN} --version
  # Setup python env
  - pip install -r requirements.txt
  # Install node dependencies
  - npm install

script:
  - pytest
